[[llm.clients]]
name = "moonshot"
provider = "moonshot"
temperature = 1.0
thinking_enabled = true
model = "kimi-k2.5"
url = "https://api.moonshot.cn/v1"
api_key = "sk-Fcdscsdcsdcsdcasdcscsdcdscsdcsd"

[agent]
max_steps = 5

[tools]
script_dir = "script"
mcp_dir = "mcp"
mcp_servers = []

[skills]
skill_dirs = ["skills"]

[prompt]
system_prompt_file = "prompt/sys_prompt/core_sys.md"
agent_role_file = "prompt/layers/agent_role.md"
skill_rules_file = "prompt/layers/skill_rules.md"
tool_rules_file = "prompt/layers/tool_rules.md"

[logging]
log_dir = "log"
